---
version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/my-bucket;
        mc cp -r /data/* myminio/my-bucket;
      "
    volumes:
      - ./minio_data:/data

  python_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

volumes:
  minio_data:
